import sqlite3
import cv2
import time
from utils.capture_utils import open_camera, capture_frame, detect_face, draw_faces, generate_face_embeddings, release_camera
from utils.storage_utils import createStudent, save_embeddings, cursor, conn

def register_new_face():
    print("\n" + "═"*40)
    print("📝 BIOCRYPT - STUDENT REGISTRATION")
    print("═"*40)

    name = input("👤 Enter Student Full Name: ").strip()
    reg_no = input("🎓 Enter Registration Number: ").strip()

    if not name or not reg_no:
        print("❌ Error: All fields are required. Registration aborted.")
        return

    cursor.execute(('SELECT id FROM Students WHERE registrationNo = ?'), (reg_no,))
    if cursor.fetchone():
        print(f"❌ Error: A student with registration number '{reg_no}' already exists!")
        return

    capture = open_camera()
    embeddings = None
    stable_start = None
    stable_duration = 2.0

    print("\n📷 Looking for face... Please keep your head steady.")

    while True:
        try:
            frame = capture_frame(capture)
        except Exception:
            break
        
        face_locations = detect_face(frame)
        draw_faces(frame, face_locations)

        # Show video
        # cv2.imshow("Register Face", frame)

        if face_locations and embeddings is None:
            if stable_start is None:
                stable_start = time.time()
            elif time.time() - stable_start >= stable_duration:
                embeddings = generate_face_embeddings(frame, face_locations)
                if embeddings:
                    #print("✅ Face embedding captured:", embeddings[0][:5])
                    print("✅ Face template successfully processed.")
                    break
                else:
                    print("⚠️ Face detected but embedding extraction failed. Retrying...")
                    stable_start = None
        else:
            stable_start = None  # reset if face disappears

        # Allow emergency manual breakout
        if cv2.waitKey(1) & 0xFF == ord('q'):
            print("❌ Registration canceled by user.")
            release_camera(capture)
            return

    release_camera(capture)

    if embeddings:
        try:
            print("\n💾 Committing user and cryptographic templates to security storage...")

            # Step A: Register Student profile
            createStudent(name, reg_no)

            # Step B: Pull the auto-increment ID generated by SQLite for this insert
            student_internal_id = cursor.lastrowid

            # Step C: Encrypt & Save using the retrieved internal row identity
            save_embeddings(student_internal_id, embeddings[0])

            print(f"🎉 Success! {name} has been enrolled in BioCrypt.")
            
        except sqlite3.Error as db_error:
            print(f"❌ Database Transaction Failure: {db_error}")

    else:
        print("❌ Registration aborted: No face captured.")

if __name__ == '__main__':

    register_new_face()
